INSERT INTO CATEGORY VALUES(1, 100, '여성의류');
INSERT INTO CATEGORY VALUES(2, 200, '남성의류');
INSERT INTO CATEGORY VALUES(3, 300, '신발');
INSERT INTO CATEGORY VALUES(4, 400, '가방');
INSERT INTO CATEGORY VALUES(5, 500, '시계/주얼리');
INSERT INTO CATEGORY VALUES(6, 600, '패션 액세서리');
INSERT INTO CATEGORY VALUES(7, 700, '디지털/가전');
INSERT INTO CATEGORY VALUES(8, 800, '스포츠/레저');